Spring boot migration
evil-face/spring-gym pull request #1
Opened 2023-10-16 14:07 UTC by evil-face

Please check my migration code

2023-10-25 14:02 UTC, Faworit requested changes

2023-10-26 06:04 UTC, evil-face commented on src/main/java/epam/xstack/controller/TraineeController.java
> +        Optional<Trainee> updatedTraineeOpt = traineeService.update(txID, traineeToUpdate);
Discussed: txID is a transaction ID which is passed through services for logging

2023-10-26 06:30 UTC, evil-face commented on src/main/java/epam/xstack/controller/TraineeController.java
>          traineeToUpdate.setId(id);
Discussed: txID is a transaction ID which is passed through services for logging

2023-10-26 06:31 UTC, evil-face commented on src/main/java/epam/xstack/exception/ValidationException.java
> +public final class ValidationException extends RuntimeException {
Will discuss during next call - #1

2023-10-26 06:33 UTC, evil-face commented on src/main/java/epam/xstack/controller/TrainingController.java
> +        List<TrainingType> response = trainingService.findAllTrainingTypes();
Done.

2023-10-26 06:37 UTC, evil-face commented on src/main/java/epam/xstack/model/User.java
> +    public Boolean getIsActive() {
Will discuss during next call - 2

2023-10-26 06:37 UTC, evil-face commented on src/main/java/epam/xstack/model/User.java
> +    public void setIsActive(Boolean active) {
Will discuss during next call - 2

2023-10-26 06:48 UTC, evil-face commented on src/main/java/epam/xstack/model/User.java
> +    public void setIsActive(Boolean active) {
Done.

2023-10-26 06:48 UTC, evil-face commented on src/main/java/epam/xstack/model/User.java
> +    public void setIsActive(Boolean active) {
Done.

2023-10-26 06:51 UTC, evil-face commented on src/main/java/epam/xstack/repository/TraineeRepository.java
> +    List<Trainee> findByUsernameStartingWith(String username);
It's used in `TraineeService.checkIfNotRegisteredYet()` method. 
It will find all usernames like `name.surname`, `name.surname1`, `name.surname2` and return them to handle person registration for the second time (duplicates).

2023-10-26 06:52 UTC, evil-face commented on src/main/java/epam/xstack/repository/TrainingSpecs.java
> +    private TrainingSpecs() {
It was SonarQube's suggestion: to add private constructor because it's a utility class with all static methods and we wouldn't want it to somehow be instantiated.

2023-10-26 06:53 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
> +    public TraineeService(UserService userService, TraineeRepository traineeRepository,
Not using Lombok in this project. Tell me if I need to.
Can discuss it during our next call - 3

2023-10-26 06:54 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
> +        authService.authenticate(txID, id, username, password);
`txID` - transaction ID to pass around for logging
`id` - actually trainee id from request.

Should I rename it to `traineeId`?

2023-10-26 06:59 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
> +        Optional<Trainee> traineeOpt = traineeRepository.findById(id);
Hmm, couldn't just do `Optional<Trainee> traineeOpt = traineeRepository.findById(id).ifPresent(value -> value.setUsername(null));` because `ifPresent()` returns `void`

2023-10-26 07:00 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
> +        traineeOpt.ifPresent(value -> value.setUsername(null));
Will discuss it during our next call - 4.
In short: to handle data which gets to DTO in response

2023-10-26 07:43 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
> +        return traineeRepository.findById(updatedTrainee.getId())
Okay! Not quite a stream, just Optional mapping. I've changed it to that for readability:
```java
Optional<Trainee> traineeOptional = traineeRepository.findById(id);

        if (traineeOptional.isPresent()) {
            Trainee existingTrainee = traineeOptional.get();
            updateFields(existingTrainee, updatedTrainee);

            traineeRepository.save(existingTrainee);
            LOGGER.info("TX ID: {} — Successfully updated trainee with username '{}' and id '{}'",
                    txID, existingTrainee.getUsername(), existingTrainee.getId());

            return Optional.of(modelMapper.map(existingTrainee, TraineeResponseDTO.class));
        }
```

2023-10-26 07:43 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
> +        Trainee trainee = traineeRepository.getReferenceById(id);
Agree. Changed to 
```java
Optional<Trainee> traineeOpt = traineeRepository.findById(id);

        if (traineeOpt.isPresent()) {
            Trainee trainee = traineeOpt.get();
            trainee.setIsActive(newStatus);

            traineeRepository.save(trainee);
            LOGGER.info("TX ID: {} — Successfully changed status for trainee with  id '{}' to '{}'", txID, id, newStatus);
        } else {
            throw new NoSuchTraineeExistException(txID);
        }
```

2023-10-26 07:49 UTC, evil-face commented on src/main/java/epam/xstack/model/Trainee.java
> -
Done.

2023-10-26 07:50 UTC, evil-face commented on src/main/java/epam/xstack/model/Trainer.java
> -
Done.

2023-10-26 07:50 UTC, evil-face commented on src/main/java/epam/xstack/model/Trainer.java
> -
Done.

2023-10-26 07:50 UTC, evil-face commented on src/main/java/epam/xstack/model/TrainingType.java
> -
Done everywhere.

2023-10-26 08:14 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
>      public List<Training> getTrainingsWithFiltering(String txID, long id, String username, String password,
Agree, refactored: moved to TrainingService

2023-10-26 08:15 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
> +        trainings.forEach(training -> training.setTrainee(null));
Will discuss it during our next call - 4.
In short: to handle data which gets to DTO in response

2023-10-26 08:21 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
> +        allTrainers.removeAll(assignedTrainers);
Done.

2023-10-26 08:23 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
> +        allTrainers.forEach(trainer -> {
Will discuss it during our next call - 4.
In short: to handle data which gets to DTO in response

2023-10-26 08:26 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
> +            Trainee trainee = traineeRepository.getReferenceById(id);
Agree, changed to
```java
Optional<Trainee> traineeOpt = traineeRepository.findById(id);
        
        if (traineeOpt.isPresent()) {
            Trainee trainee = traineeOpt.get();
            trainee.setTrainers(new HashSet<>(updatedList));

            traineeRepository.save(trainee);
            LOGGER.info("TX ID: {} — Successfully updated trainee's list of trainers for id '{}' with '{}'"
                    + " trainers", txID, id, updatedList.size());
        } else {
            throw new NoSuchTraineeExistException(txID);
        }
```

2023-10-26 08:26 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
> +            if (!trainee.getUsername().equals(traineeRequestDTO.getUsername())) {
Yes, it totally refactored in Spring Security

2023-10-26 08:27 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
> +        updatedList.forEach(trainer -> {
Will discuss it during our next call - 4.
In short: to handle data which gets to DTO in response

2023-10-26 08:31 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
>                  .filter(trainer -> traineeRequestDTO.getTrainers().contains(trainer.getUsername()))
Yeah. We take all existing trainers (confirmed from repo) and during filtering leave only those whose `username` is equal to usernames in request DTO.

For example, if request has some invalid trainer usernames, they will not get to final updated list. That's why I called it 'verifyTrainers`.

Could you provide an example of better naming?

2023-10-26 08:32 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
> +        List<Trainee> candidates = traineeRepository.findByUsernameStartingWith(
Will discuss it during our next call - 5.

2023-10-26 08:33 UTC, evil-face commented on src/main/java/epam/xstack/service/TrainerService.java
>      public Trainer createTrainer(String txID, Trainer newTrainer) {
Done.

2023-10-26 08:35 UTC, evil-face commented on src/main/java/epam/xstack/service/TrainerService.java
> +        authService.authenticate(txID, updatedTrainer.getId(),
Refactored in Spring Security

2023-10-27 04:27 UTC, evil-face commented on src/main/java/epam/xstack/service/TrainerService.java
> +        trainerOpt.ifPresent(value -> value.setUsername(null));
It was refactored, now it returns DTO

2023-10-27 04:29 UTC, evil-face commented on src/main/java/epam/xstack/service/TrainerService.java
> +        if (trainerOpt.isEmpty()) {
I don't think so, because it's passed to another service for evaluation (existing or not). 
Will discuss it during our next call - 6.

2023-10-27 04:35 UTC, evil-face commented on src/main/java/epam/xstack/service/TrainerService.java
> +        Optional<TrainingType> trainingTypeOpt = trainingTypeRepository.findById(
Agree, I see leaking logic. Refactored.

2023-11-01 15:31 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
> +        authService.authenticate(txID, id, username, password);
Decided to rename

2023-11-02 04:38 UTC, evil-face commented on src/main/java/epam/xstack/exception/ValidationException.java
> +public final class ValidationException extends RuntimeException {
Decided to leave it

2023-11-02 04:38 UTC, evil-face commented on src/main/java/epam/xstack/model/Trainee.java
>      @OneToMany(mappedBy = "trainee", cascade = CascadeType.REMOVE)
Decided to leave it

2023-11-02 04:41 UTC, evil-face commented on src/main/java/epam/xstack/repository/TraineeRepository.java
> +    List<Trainee> findByUsernameStartingWith(String username);
Was explained during call.

2023-11-02 04:41 UTC, evil-face commented on src/main/java/epam/xstack/repository/TrainingSpecs.java
> +    private TrainingSpecs() {
Decided to leave it.

2023-11-02 04:49 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
> +        Optional<Trainee> traineeOpt = traineeRepository.findById(id);
Decided to change mapping approach

2023-11-02 04:50 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
> +        traineeOpt.ifPresent(value -> value.setUsername(null));
Decided to change mapping approach

2023-11-02 04:50 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
> +        trainings.forEach(training -> training.setTrainee(null));
Decided to change mapping approach

2023-11-02 04:50 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
> +        allTrainers.forEach(trainer -> {
Decided to change mapping approach

2023-11-02 04:50 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
> +        updatedList.forEach(trainer -> {
Decided to change mapping approach

2023-11-02 04:52 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
>                  .filter(trainer -> traineeRequestDTO.getTrainers().contains(trainer.getUsername()))
Decided to move this method to `TrainerService`

2023-11-02 04:52 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
> +        List<Trainee> candidates = traineeRepository.findByUsernameStartingWith(
Was explained during call

2023-11-02 04:52 UTC, evil-face commented on src/main/java/epam/xstack/service/TraineeService.java
> +    public TraineeService(UserService userService, TraineeRepository traineeRepository,
Decided to try to add Lombok to some classes as a learning exercise.

2023-11-02 04:53 UTC, evil-face commented on src/main/java/epam/xstack/service/TrainerService.java
> +        if (trainerOpt.isEmpty()) {
Changed a little

2023-11-02 04:54 UTC, evil-face commented on src/main/java/epam/xstack/service/TrainerService.java
> +        Optional<TrainingType> trainingTypeOpt = trainingTypeRepository.findById(
Asked mentor for a way to resolve circular dependency

2023-11-08 10:27 UTC, evil-face commented
Decided to merge during call with Faworit.

2023-11-08 10:27 UTC, merged

2023-11-08 10:27 UTC, evil-face commented
Decided to merge during call with Faworit.